# Generated by Django 5.0.3 on 2024-03-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_remote_employee",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_live",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
